#!/usr/bin/env python3
"""
Batch-audit all articles that don't yet have a report in research/agents/reports/.
Usage: python research/agents/batch_audit.py [--model MODEL] [--resume]
  --model:   Override LLM model (default: from env or gpt-4o-mini)
  --resume:  Skip slugs that already have a report file
"""

import os, sys, glob, time, json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
REPORTS_DIR = PROJECT_ROOT / "research" / "agents" / "reports"
ARTICLES_DIR = PROJECT_ROOT / "src" / "content" / "articles"

# ─── Article list ────────────────────────────────────────────────────────

ALL_SLUGS = sorted([p.stem for p in ARTICLES_DIR.glob("*.mdx")])
EXISTING_REPORTS = {p.stem for p in REPORTS_DIR.glob("*.md")}
# Skip non-article reports
EXISTING_REPORTS.discard("agent-audit-and-strategy-report")
EXISTING_REPORTS.discard("quality-gates-report")

UNAUDITED = [s for s in ALL_SLUGS if s not in EXISTING_REPORTS]
print(f"Total articles: {len(ALL_SLUGS)}")
print(f"Already audited: {len(EXISTING_REPORTS)}")
print(f"Remaining: {len(UNAUDITED)}")
print()

# ─── Imports ─────────────────────────────────────────────────────────────

# Add research/agents to path
sys.path.insert(0, str(SCRIPT_DIR))
from content_auditor import (
    fetch_and_extract, TextMetrics, ContentAuditor, generate_report
)

# ─── Config ──────────────────────────────────────────────────────────────

from dotenv import load_dotenv
load_dotenv()

API_KEY = os.environ.get("OPENAI_API_KEY") or os.environ.get("LLM_API_KEY")
if not API_KEY:
    print("FATAL: LLM_API_KEY not set")
    sys.exit(1)

MODEL = None
RESUME = False
for arg in sys.argv[1:]:
    if arg.startswith("--model="):
        MODEL = arg.split("=", 1)[1]
    elif arg == "--resume":
        RESUME = True

MODEL = MODEL or os.environ.get("OPENAI_MODEL") or os.environ.get("LLM_MODEL", "gpt-4o-mini")
BASE_URL = os.environ.get("OPENAI_BASE_URL") or os.environ.get("LLM_BASE_URL", "https://api.openai.com/v1")
SITE_BASE = "https://www.praveentechworld.com"

print(f"Model: {MODEL}")
print(f"Base URL: {BASE_URL}")
print(f"Site: {SITE_BASE}")
print(f"Resume mode: {RESUME}")
print()

# ─── Batch loop ──────────────────────────────────────────────────────────

auditor = ContentAuditor(api_key=API_KEY, model=MODEL)

stats = {"ok": 0, "skip": 0, "fail": 0, "total": len(UNAUDITED)}
timings = []

for i, slug in enumerate(UNAUDITED, 1):
    report_path = REPORTS_DIR / f"{slug}.md"

    if RESUME and report_path.exists():
        print(f"[{i}/{len(UNAUDITED)}] SKIP (exists): {slug}")
        stats["skip"] += 1
        continue

    url = f"{SITE_BASE}/blog/{slug}"
    print(f"[{i}/{len(UNAUDITED)}] AUDIT: {url}")
    t0 = time.time()

    try:
        # Fetch
        article_text = fetch_and_extract(url, timeout=30)
        word_count = len(article_text.split())
        print(f"  Fetched: {len(article_text):,} chars, ~{word_count} words")

        # Metrics
        tm = TextMetrics(article_text)
        metrics = tm.summary()

        # Report key stats
        print(f"  Burstiness={metrics['burstiness']}  LexDiv={metrics['lexical_diversity']}  "
              f"Flesch={metrics['flesch_reading_ease']}  EmDash={metrics['em_dash_count']}")

        # LLM analysis
        report = auditor.analyze(article_text, metrics, debug=False)
        fix_count = len(report.actionable_fixes) if report.actionable_fixes else 0
        print(f"  Score={report.ai_score_percentage}/100  Fixes={fix_count}")

        # Save report
        md = generate_report(url, article_text, metrics, report)
        report_path.write_text(md, encoding="utf-8")
        print(f"  Saved: {report_path}")

        stats["ok"] += 1
        elapsed = time.time() - t0
        timings.append(elapsed)
        print(f"  Done in {elapsed:.1f}s")

    except Exception as e:
        print(f"  FAILED: {e}")
        stats["fail"] += 1
        # Save a minimal error report
        error_md = (
            f"# Content Audit Report — {slug}\n\n"
            f"**URL:** {url}\n"
            f"**Date:** (error)\n\n"
            f"## Error\n\n"
            f"```\n{str(e)}\n```\n\n"
            f"---\n*Generated by Content Auditor*\n"
        )
        report_path.write_text(error_md, encoding="utf-8")
        print(f"  Saved error report: {report_path}")

    # Brief pause between requests
    if i < len(UNAUDITED):
        time.sleep(1.5)

# ─── Summary ─────────────────────────────────────────────────────────────

total_elapsed = sum(timings)
print()
print("=" * 60)
print(f"  BATCH AUDIT COMPLETE")
print(f"  Total:  {stats['total']} articles")
print(f"  OK:     {stats['ok']}")
print(f"  Skip:   {stats['skip']}")
print(f"  Fail:   {stats['fail']}")
if timings:
    avg = total_elapsed / len(timings)
    print(f"  Avg:    {avg:.1f}s per article")
    print(f"  Total:  {total_elapsed:.0f}s ({total_elapsed/60:.1f} min)")
print("=" * 60)
print(f"Reports in: {REPORTS_DIR}")
