import { fileURLToPath } from "url";
import path from "path";
import fs from "fs";
import { log, ensureDir } from "./lib/shared.mjs";
import { appendToReport } from "./lib/report.mjs";
import { devtoPost, parseArticle } from "./lib/syndication.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const AGENTS_DIR = path.resolve(__dirname);
const STATE_FILE = path.join(AGENTS_DIR, "state.json");
const ARTICLES_DIR = path.resolve(__dirname, "../../src/content/articles");

const WARMUP_ARTICLES = [
  "how-to-use-chatgpt-to-summarize-long-pdfs-for-free.mdx",
  "android-battery-draining-fast-after-update-7-proven-fixes-for-2026.mdx",
];

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
  } catch {
    return { syndicated: [], devtoSetupDone: false };
  }
}

function saveState(state) {
  ensureDir(AGENTS_DIR);
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), "utf-8");
}

export async function setupDevto() {
  log("[Dev.to Setup] Starting...");
  const apiKey = process.env.DEVTO_API_KEY;
  if (!apiKey) {
    log("[Dev.to Setup] No DEVTO_API_KEY in .env. Skipping.");
    return { ok: false, reason: "no key" };
  }

  const state = loadState();
  const results = [];

  // Manual instructions
  log("");
  log("=== MANUAL STEPS REQUIRED ===");
  log("Go to https://dev.to/settings and update:");
  log("  Name: Praveen");
  log("  Bio: I write practical tech guides to help students and office");
  log("       workers solve real problems — from fixing Android battery");
  log("       drain to automating workflows with free tools.");
  log("  Location: Dubai");
  log("  Website URL: https://www.praveentechworld.com");
  log("  Twitter: @praveenwithapen");
  log("  Profile picture: Generate at https://api.dicebear.com/7.x/avataaars/svg?seed=Praveen");
  log("  Follow tags: tech, webdev, android, windows, privacy, productivity, beginners, tutorial, ai, chatgpt, automation");
  log("==========================");
  log("");

  results.push({ step: "profile", ok: true, note: "Manual — update at dev.to/settings" });

  // Post warm-up articles
  log("[Dev.to Setup] Posting warm-up articles...");
  for (const file of WARMUP_ARTICLES) {
    const filePath = path.join(ARTICLES_DIR, file);
    if (!fs.existsSync(filePath)) {
      log(`  Skipped (not found): ${file}`);
      continue;
    }
    const article = parseArticle(filePath);
    if (!article) { log(`  Skipped (parse failed): ${file}`); continue; }

    try {
      const post = await devtoPost(article, apiKey);
      log(`  Published: ${article.title} → ${post?.url || "OK"}`);
      state.syndicated = state.syndicated || [];
      state.syndicated.push(file);
      results.push({ step: `warmup:${file}`, ok: true, url: post?.url || "" });
    } catch (err) {
      log(`  Failed: ${file} — ${err.message}`);
      results.push({ step: `warmup:${file}`, ok: false, error: err.message });
    }

    await new Promise((r) => setTimeout(r, 5000));
  }

  state.devtoSetupDone = true;
  saveState(state);

  const lines = [
    "## Dev.to — Setup Complete",
    `**Date:** ${new Date().toISOString()}`,
    "",
    "### Warm-up Articles",
    ...results.filter((r) => r.step.startsWith("warmup")).map((r) =>
      `- ${r.ok ? "✅" : "❌"} ${r.file || r.step}${r.url ? ` — ${r.url}` : ""}${r.error ? ` — ${r.error}` : ""}`
    ),
    "",
    "### Manual Configuration Needed",
    "1. Go to https://dev.to/settings",
    "2. Set Name: Praveen, Bio, Location: Dubai, Website URL",
    "3. Upload profile picture (DiceBear: https://api.dicebear.com/7.x/avataaars/svg?seed=Praveen)",
    "4. Follow tech tags manually",
    "",
    "*Auto-generated by Dev.to Setup*",
  ];
  appendToReport("Dev.to Setup", lines.join("\n"));

  log(`[Dev.to Setup] Done. Warm-up: ${results.filter((r) => r.step.startsWith("warmup") && r.ok).length}/${WARMUP_ARTICLES.length} published.`);
  return { ok: true, results };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  setupDevto().catch(console.error);
}
