import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { log, ensureDir } from "./lib/shared.mjs";
import { appendToReport } from "./lib/report.mjs";
import { devtoPost, hashnodePost, linkedinPost, bloggerPost, parseArticle, getNewArticles } from "./lib/syndication.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const AGENTS_DIR = path.resolve(__dirname);
const STATE_FILE = path.join(AGENTS_DIR, "state.json");
const ARTICLES_DIR = path.resolve(__dirname, "../../src/content/articles");

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
  } catch {
    return { syndicated: [], hashnodePublicationId: null };
  }
}

function saveState(state) {
  ensureDir(AGENTS_DIR);
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2), "utf-8");
}

export async function runSyndication() {
  log("[Syndication] Starting...");
  const devtoKey = process.env.DEVTO_API_KEY;
  const hashnodePat = process.env.HASHNODE_PAT;
  const state = loadState();
  const results = [];

  // Only process 1 article per run to avoid rate limits
  const newFiles = getNewArticles(state.syndicated || []);
  if (newFiles.length === 0) {
    log("[Syndication] No new articles to syndicate.");
    return { ok: true, syndicated: 0, total: 0 };
  }

  const file = newFiles[0];
  const filePath = path.join(ARTICLES_DIR, file);
  if (!fs.existsSync(filePath)) {
    log(`  Skipped (missing): ${file}`);
    return { ok: true, syndicated: 0, total: 0 };
  }

  const article = parseArticle(filePath);
  if (!article) {
    log(`  Skipped (parse failed): ${file}`);
    return { ok: true, syndicated: 0, total: 0 };
  }

  // Post to Dev.to
  if (devtoKey) {
    try {
      const post = await devtoPost(article, devtoKey);
      log(`  ✓ Dev.to: "${article.title}" → ${post?.url || "OK"}`);
      results.push({ platform: "devto", file, ok: true, url: post?.url || "" });
      await new Promise((r) => setTimeout(r, 3000));
    } catch (err) {
      const msg = err.message || "";
      if (msg.includes("429") || msg.includes("Rate limit")) {
        log(`  ⏳ Dev.to rate limited, will retry next run`);
        return { ok: true, syndicated: 0, total: 0, rateLimited: true };
      }
      log(`  ✗ Dev.to FAILED: ${file} — ${err.message}`);
      results.push({ platform: "devto", file, ok: false, error: err.message });
    }
  }

  // Hashnode: API is now a paid offering (since 2026-05-13), skipping.

  // LinkedIn (requires OAuth 2.0 setup)
  const linkedinToken = process.env.LINKEDIN_ACCESS_TOKEN;
  if (linkedinToken) {
    try {
      const post = await linkedinPost(article, linkedinToken);
      if (post) {
        log(`  ✓ LinkedIn: "${article.title}"`);
        results.push({ platform: "linkedin", file, ok: true });
        await new Promise((r) => setTimeout(r, 2000));
      }
    } catch (err) {
      log(`  ✗ LinkedIn FAILED: ${file} — ${err.message}`);
      results.push({ platform: "linkedin", file, ok: false, error: err.message });
    }
  }

  // Blogger (requires OAuth 2.0 setup)
  const bloggerToken = process.env.BLOGGER_ACCESS_TOKEN;
  const bloggerBlogId = process.env.BLOGGER_BLOG_ID;
  if (bloggerToken && bloggerBlogId) {
    try {
      const post = await bloggerPost(article, bloggerToken, bloggerBlogId);
      if (post) {
        log(`  ✓ Blogger: "${article.title}"`);
        results.push({ platform: "blogger", file, ok: true });
        await new Promise((r) => setTimeout(r, 2000));
      }
    } catch (err) {
      log(`  ✗ Blogger FAILED: ${file} — ${err.message}`);
      results.push({ platform: "blogger", file, ok: false, error: err.message });
    }
  }

  // Mark as syndicated only if at least one platform succeeded
  const anySuccess = results.some((r) => r.ok);
  if (anySuccess) {
    state.syndicated = state.syndicated || [];
    state.syndicated.push(file);
    saveState(state);
  }

  // Report
  if (results.length) {
    const lines = [
      "## Syndication — Run",
      `**Date:** ${new Date().toISOString()}`,
      ...results.map((r) =>
        `- ${r.ok ? "✅" : "❌"} [${r.platform}] ${r.file}${r.url ? ` — ${r.url}` : ""}${r.error ? ` — ${r.error}` : ""}`
      ),
      "",
      `*${results.filter((r) => r.ok).length}/${results.length} succeeded*`,
      "",
      "*Auto-generated by Syndication Agent*",
    ];
    appendToReport("Syndication", lines.join("\n"));
  }

  log(`[Syndication] Done. ${results.filter((r) => r.ok).length}/${results.length} posts succeeded.`);
  return { ok: true, syndicated: results.filter((r) => r.ok).length, total: results.length };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runSyndication().catch(console.error);
}
