import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import pagefind from "astro-pagefind";

function rehypeExternalLinks() {
  return (tree) => {
    function visit(node) {
      if (node.type === "element" && node.tagName === "a" && node.properties && node.properties.href) {
        const href = String(node.properties.href);
        if (href.startsWith("http://") || href.startsWith("https://")) {
          if (!href.includes("praveentechworld.com")) {
            node.properties.rel = ["nofollow", "noopener", "noreferrer"];
            node.properties.target = "_blank";
          }
        }
      }
      if (node.children) {
        node.children.forEach(visit);
      }
    }
    visit(tree);
  };
}

export default defineConfig({
  site: "https://www.praveentechworld.com",
  trailingSlash: "never",
  redirects: {
    "/blog/chrome-removes-ai-privacy-wording-what-googles-on-device-data-claim-means-for-us": "/blog/chrome-removes-ai-privacy-wording-google-on-device-data",
    "/blog/ga4-shows-realtime-users-but-standard-reports-stay-blank-fix-event-processing-an": "/blog/ga4-shows-realtime-users-but-reports-blank-fix-processing",
    "/blog/sitemap-urls-are-blocked-by-robotstxt-clean-up-your-sitemap-and-resubmit-it-in-g": "/blog/sitemap-urls-blocked-by-robotstxt-clean-and-resubmit",
    "/blog/how-to-fix-windows-11-update-errors-in-2026-complete-troubleshooting-guide": "/blog/fix-windows-11-update-errors-2026-troubleshooting",
    "/blog/automate-your-daily-workflow-in-2026-free-tools-and-real-examples": "/blog/how-to-automate-your-daily-workflow-with-free-tools-in-2026-complete-guide",
    "/p/contact-us.html": "/contact",
    "/p/contact-us.html?m=1": "/contact",
    "/blog/post-5/": "/blog",
    "/blog/post-8/": "/blog",
    "/categories/youtube/": "/blog",
    "/tags/tech/": "/tag/tech",
    "/tag/AI-AUTOMATION": "/tag/ai-automation",
    "/tag/PYTHON": "/tag/python",
    "/tag/CONTENT-AUDITING": "/tag/content-auditing",
    "/tag/BLOGGING": "/tag/blogging",
    "/tag/DEEPSEEK": "/tag/deepseek",
    "/tag/SEO": "/tag/seo",
    "/tag/AI": "/tag/ai",
    "/tag/DATAPRIVACY": "/tag/dataprivacy",
    "/tag/HIGHEREDUCATION": "/tag/highereducation",
    "/tag/EDTECH": "/tag/edtech",
    "/tag/STUDENTDATA": "/tag/studentdata",
    "/tag/PRIVACYSECURITY": "/tag/privacysecurity",
    "/tag/WEBSITE": "/tag/website",
    "/tag/TUTORIAL": "/tag/tutorial",
    "/tag/MICROSOFT-AI": "/tag/microsoft-ai",
    "/tag/OFFICE-PRODUCTIVITY": "/tag/office-productivity",
    "/tag/FUTURE-OF-WORK": "/tag/future-of-work",
    "/tag/AI-TOOLS": "/tag/ai-tools",
    "/tag/CAREER-GROWTH": "/tag/career-growth",
    "/tag/AI-AGENTS": "/tag/ai-agents",
    "/tag/AUTONOMOUS-AI": "/tag/autonomous-ai",
    "/tag/AGENT-SANDBOX": "/tag/agent-sandbox",
    "/tag/BREAKING-AI-CHATBOX": "/tag/breaking-ai-chatbox",
    "/tag/BERKELEY-CS": "/tag/berkeley-cs",
    "/tag/SQLITE": "/tag/sqlite",
    "/tag/ANDROID-BATTERY-DRAIN": "/tag/android-battery-drain",
    "/tag/FIX-BATTERY-ISSUES": "/tag/fix-battery-issues",
    "/tag/ANDROID-UPDATE": "/tag/android-update",
    "/tag/CACHE-CLEARING": "/tag/cache-clearing",
    "/tag/APP-OPTIMIZATION": "/tag/app-optimization",
    "/tag/BATTERY-CALIBRATION": "/tag/battery-calibration",
    "/tag/ANDROID-CHARGING-FIX": "/tag/android-charging-fix",
    "/tag/TROUBLESHOOT-ANDROID-BATTERY": "/tag/troubleshoot-android-battery",
    "/tag/PHONE-NOT-CHARGING": "/tag/phone-not-charging",
    "/tag/USB-C-PORT-CLEANING": "/tag/usb-c-port-cleaning",
    "/tag/DIY-MOBILE-REPAIR": "/tag/diy-mobile-repair",
    "/tag/SERVER-MONITORING": "/tag/server-monitoring",
    "/tag/PYTHON-AUTOMATION": "/tag/python-automation",
    "/tag/HEALTH-CHECKS": "/tag/health-checks",
    "/tag/SYSADMIN": "/tag/sysadmin",
    "/tag/DEVOPS": "/tag/devops",
    "/tag/TLS-CERTIFICATES": "/tag/tls-certificates",
    "/tag/AUTOMATION": "/tag/automation",
    "/tag/PRODUCTION": "/tag/production",
    "/tag/AVATAR-GENERATION": "/tag/avatar-generation",
    "/tag/CONTENT-CREATION": "/tag/content-creation",
    "/tag/IMAGE-GENERATION": "/tag/image-generation",
    "/tag/FREE-AI": "/tag/free-ai",
    "/tag/LOGO-GENERATOR": "/tag/logo-generator",
    "/tag/BRANDING": "/tag/branding",
    "/tag/VIDEO-GENERATION": "/tag/video-generation",
    "/tag/OPEN-SOURCE": "/tag/open-source",
    "/tag/FREE-SOFTWARE": "/tag/free-software",
    "/tag/PRODUCTIVITY": "/tag/productivity",
    "/tag/TOOLS": "/tag/tools",
    "/tag/ALTERNATIVES": "/tag/alternatives",
    "/tag/MONEY-SAVING": "/tag/money-saving",
    "/tag/PRIVACY": "/tag/privacy",
    "/tag/SECURITY": "/tag/security",
    "/tag/VPN": "/tag/vpn",
    "/tag/ONLINE-SAFETY": "/tag/online-safety",
    "/tag/FREE": "/tag/free",
    "/tag/PASSWORD-MANAGER": "/tag/password-manager",
    "/tag/PASSKEYS": "/tag/passkeys",
    "/tag/ENCRYPTION": "/tag/encryption",
    "/tag/CYBERSECURITY": "/tag/cybersecurity",
    "/tag/AGENTS": "/tag/agents",
    "/tag/AUTONOMOUS": "/tag/autonomous",
    "/tag/SWE-AGENT": "/tag/swe-agent",
    "/tag/PLAYWRIGHT": "/tag/playwright",
    "/tag/LLM": "/tag/llm",
    "/tag/CHATGPT": "/tag/chatgpt",
    "/tag/EXCEL": "/tag/excel",
    "/tag/FINANCIAL-DATA": "/tag/financial-data",
    "/tag/OFFICE-TIPS": "/tag/office-tips",
    "/tag/AI-PRIVACY": "/tag/ai-privacy",
    "/tag/DATA-PRIVACY": "/tag/data-privacy",
    "/tag/WORK": "/tag/work",
    "/tag/ADOPTION": "/tag/adoption",
    "/tag/AI-AT-WORK": "/tag/ai-at-work",
    "/tag/CLAUDE": "/tag/claude",
    "/tag/GEMINI": "/tag/gemini",
    "/tag/COMPARISON": "/tag/comparison",
    "/tag/CHROME-PRIVACY": "/tag/chrome-privacy",
    "/tag/AI-PRIVACY-CHANGES": "/tag/ai-privacy-changes",
    "/tag/ON-DEVICE-DATA": "/tag/on-device-data",
    "/tag/GOOGLE-CHROME-UPDATES": "/tag/google-chrome-updates",
    "/tag/PRIVACY-CONCERNS": "/tag/privacy-concerns",
    "/tag/TECH-NEWS-2026": "/tag/tech-news-2026",
    "/tag/WEBSITE-SETUP": "/tag/website-setup",
    "/tag/LLM-ORCHESTRATION": "/tag/llm-orchestration",
    "/tag/COST-MANAGEMENT": "/tag/cost-management",
    "/tag/WORKFLOW-AUTOMATION": "/tag/workflow-automation",
    "/tag/DATA-PROTECTION": "/tag/data-protection",
    "/tag/UNIVERSITY-SECURITY": "/tag/university-security",
    "/tag/FERPA": "/tag/ferpa",
    "/tag/GDPR": "/tag/gdpr",
    "/tag/HIGHER-EDUCATION": "/tag/higher-education",
    "/tag/API-COSTS": "/tag/api-costs",
    "/tag/COST-OPTIMIZATION": "/tag/cost-optimization",
    "/tag/TOKEN-DASHBOARD": "/tag/token-dashboard",
    "/tag/AWS": "/tag/aws",
    "/tag/CLOUD-COSTS": "/tag/cloud-costs",
    "/tag/INFRASTRUCTURE": "/tag/infrastructure",
    "/tag/INCIDENT-RESPONSE": "/tag/incident-response",
    "/tag/CLI-TOOLS": "/tag/cli-tools",
    "/tag/IT-AUTOMATION": "/tag/it-automation",
    "/tag/IT": "/tag/it",
    "/tag/TECH": "/tag/tech",
    "/tag/DOCKER": "/tag/docker",
    "/tag/LINUX": "/tag/linux",
    "/tag/FILE-PERMISSIONS": "/tag/file-permissions",
    "/tag/WSL2": "/tag/wsl2",
    "/tag/WINDOWS-FIXES": "/tag/windows-fixes",
    "/tag/VIRUS-REMOVAL": "/tag/virus-removal",
    "/tag/FACTORY-RESET": "/tag/factory-reset",
    "/tag/MALWARE": "/tag/malware",
    "/tag/TROUBLESHOOTING": "/tag/troubleshooting",
    "/tag/WINDOWS-11": "/tag/windows-11",
    "/tag/UPDATE-ERRORS": "/tag/update-errors",
    "/tag/0X800F0922": "/tag/0x800f0922",
    "/tag/STUCK-UPDATES": "/tag/stuck-updates",
    "/tag/GA4": "/tag/ga4",
    "/tag/GOOGLE-ANALYTICS": "/tag/google-analytics",
    "/tag/TRACKING": "/tag/tracking",
    "/tag/GOOGLEANALYTICS": "/tag/googleanalytics",
    "/tag/EVENTS": "/tag/events",
    "/tag/WEBANALYTICS": "/tag/webanalytics",
    "/tag/WEBSITE-TRACKING": "/tag/website-tracking",
    "/tag/ANALYTICS-TROUBLESHOOTING": "/tag/analytics-troubleshooting",
    "/tag/GOOGLE-AI": "/tag/google-ai",
    "/tag/API": "/tag/api",
    "/tag/PAGETRACKING": "/tag/pagetracking",
    "/tag/ANALYTICS-GUIDE": "/tag/analytics-guide",
    "/tag/GOOGLE-SEARCH-CONSOLE": "/tag/google-search-console",
    "/tag/SEO-TOOLS": "/tag/seo-tools",
    "/tag/SEARCH-CONSOLE-TROUBLESHOOTING": "/tag/search-console-troubleshooting",
    "/tag/IT-OPERATIONS": "/tag/it-operations",
    "/tag/ACTIVE-DIRECTORY": "/tag/active-directory",
    "/tag/POWERSHELL": "/tag/powershell",
    "/tag/GPO-AUDIT": "/tag/gpo-audit",
    "/tag/SYSADMIN-GUIDE": "/tag/sysadmin-guide",
    "/tag/GOOGLE-SEARCH": "/tag/google-search",
    "/tag/WEB-DEVELOPMENT": "/tag/web-development",
    "/tag/CSS": "/tag/css",
    "/tag/WEBSITE-INDEXING": "/tag/website-indexing",
    "/tag/REGISTER-WEBSITE": "/tag/register-website",
    "/tag/SEO-BASICS": "/tag/seo-basics",
    "/tag/FREE-TOOLS": "/tag/free-tools",
    "/tag/WORKFLOW": "/tag/workflow",
    "/tag/ZAPIER": "/tag/zapier",
    "/tag/IFTTT": "/tag/ifttt",
    "/tag/WEBSITE-BUILDING": "/tag/website-building",
    "/tag/BEGINNER-GUIDE": "/tag/beginner-guide",
    "/tag/GOOGLESEARCHCONSOLE": "/tag/googlesearchconsole",
    "/tag/INDEXING": "/tag/indexing",
    "/tag/CRAWLING": "/tag/crawling",
    "/tag/SEARCHCONSOLE": "/tag/searchconsole",
    "/tag/WINDOWS": "/tag/windows",
    "/tag/GPU": "/tag/gpu",
    "/tag/NVIDIA": "/tag/nvidia",
    "/tag/BSOD": "/tag/bsod",
    "/tag/DRIVERS": "/tag/drivers",
    "/tag/SITEMAP": "/tag/sitemap",
    "/tag/TECHNICAL-SEO": "/tag/technical-seo",
    "/tag/PRODUCTIVITY-TIPS": "/tag/productivity-tips",
    "/tag/CAREER": "/tag/career",
    "/tag/GOOGLE": "/tag/google",
    "/tag/OLLAMA": "/tag/ollama",
    "/tag/LOCAL-LLM": "/tag/local-llm",
    "/tag/LOCAL-VISION-LLM": "/tag/local-vision-llm",
    "/tag/QWEN-3-6-27B": "/tag/qwen-3-6-27b",
    "/tag/OLLAMA-VLM": "/tag/ollama-vlm",
    "/tag/DIAGRAM-TO-CODE": "/tag/diagram-to-code",
    "/tag/PRIVATE-AI-INFRASTRUCTURE": "/tag/private-ai-infrastructure",
    "/tag/LOCAL-AI": "/tag/local-ai",
    "/tag/FOOOCUS": "/tag/fooocus",
    "/tag/HARDWARE": "/tag/hardware",
    "/tag/CONTENTSTRATEGY": "/tag/contentstrategy",
    "/tag/EMAIL": "/tag/email",
    "/tag/WRITING": "/tag/writing",
    "/tag/GUIDE": "/tag/guide",
    "/tag/AI-WORKFLOWS": "/tag/ai-workflows",
    "/tag/CONTENT-STRATEGY": "/tag/content-strategy",
    "/tag/ANALYTICS": "/tag/analytics",
    "/tag/SEO-WRITING": "/tag/seo-writing",
    "/tag/BLOG-OPTIMIZATION": "/tag/blog-optimization",
    "/tag/LOG-MONITORING": "/tag/log-monitoring",
    "/tag/AI-SCRIPTS": "/tag/ai-scripts",
    "/tag/ERROR-HANDLING": "/tag/error-handling",
    "/tag/AI-TOKEN-TRACKING": "/tag/ai-token-tracking",
    "/tag/FREE-AI-TOOLS": "/tag/free-ai-tools",
    "/tag/EDUCATION-TECHNOLOGY": "/tag/education-technology",
    "/tag/AI-FOR-STUDENTS": "/tag/ai-for-students",
    "/tag/TEACHER-RESOURCES": "/tag/teacher-resources",
    "/tag/COPILOT": "/tag/copilot",
    "/tag/NON-DEVELOPER": "/tag/non-developer",
    "/tag/DATABASE-AUDIT": "/tag/database-audit",
    "/tag/PROMPT-ENGINEERING": "/tag/prompt-engineering",
    "/tag/GPU-OFFLOAD": "/tag/gpu-offload",
    "/tag/OPEN-WEBUI": "/tag/open-webui",
    "/tag/RAG": "/tag/rag",
    "/tag/PC-CRASHES": "/tag/pc-crashes",
    "/tag/GPU-DIAGNOSTICS": "/tag/gpu-diagnostics",
    "/tag/PSU-TESTING": "/tag/psu-testing",
    "/tag/THERMAL-THROTTLING": "/tag/thermal-throttling",
    "/tag/RAM": "/tag/ram",
    "/tag/LOG-ANALYSIS": "/tag/log-analysis",
    "/tag/SYSADMIN-TOOLKIT": "/tag/sysadmin-toolkit",
    "/tag/BUILD-IN-PUBLIC": "/tag/build-in-public",
    "/tag/GOOGLE-RANKING": "/tag/google-ranking",
    "/tag/SEARCH-OPTIMIZATION": "/tag/search-optimization",
    "/tag/MICROSOFT-365": "/tag/microsoft-365",
    "/tag/SHADOW-AI": "/tag/shadow-ai",
    "/tag/WINDOWS-PERFORMANCE": "/tag/windows-performance",
    "/tag/SPEED-UP-PC": "/tag/speed-up-pc",
    "/tag/SLOW-PC-FIX": "/tag/slow-pc-fix",
    "/tag/WINDOWS-10": "/tag/windows-10",
    "/tag/WINDOWS-TWEAKS": "/tag/windows-tweaks",
    "/tag/SEO-CHECKLIST": "/tag/seo-checklist",
    "/tag/SITE-OPTIMIZATION": "/tag/site-optimization",
    "/tag/WEB-PERFORMANCE": "/tag/web-performance",
    "/tag/MINIMAL-WEB": "/tag/minimal-web",
    "/tag/VANILLA-JS": "/tag/vanilla-js",
    "/tag/14KB-WEBSITE": "/tag/14kb-website",
    "/tag/SQLITE-WASM": "/tag/sqlite-wasm",
    "/tag/CORE-WEB-VITALS": "/tag/core-web-vitals",
    "/tag/PAGE-SPEED": "/tag/page-speed",
    "/tag/VIRTUALIZATION": "/tag/virtualization",
    "/tag/CONTAINERS": "/tag/containers",
    "/tag/WINDOWS-TROUBLESHOOTING": "/tag/windows-troubleshooting",
    "/tag/USER-PROFILE-CORRUPTED": "/tag/user-profile-corrupted",
    "/tag/REGISTRY-FIX": "/tag/registry-fix",
    "/tag/WINDOWS-RESET": "/tag/windows-reset",
    "/tag/WINDOWS-REINSTALL": "/tag/windows-reinstall",
    "/tag/BLUE-SCREEN": "/tag/blue-screen",
    "/tag/DRIVER-ISSUES": "/tag/driver-issues",
    "/tag/WINDOWS-REPAIR": "/tag/windows-repair",
    "/tag/SLOW-PC": "/tag/slow-pc",
    "/tag/WINDOWS-SPEED": "/tag/windows-speed",
    "/tag/WINDOWS-OPTIMIZATION": "/tag/windows-optimization",
    "/tag/DEBLOAT-WINDOWS-11": "/tag/debloat-windows-11",
    "/tag/GROUP-POLICY": "/tag/group-policy",
    "/tag/POWERSHELL-SCRIPTS": "/tag/powershell-scripts",
    "/tag/TELEMETRY-BLOCKING": "/tag/telemetry-blocking",
    "/tag/SYSADMIN-TOOLS": "/tag/sysadmin-tools",
    "/tag/WINDOWS-UPDATE": "/tag/windows-update",
    "/tag/XBOX-MODE": "/tag/xbox-mode",
    "/tag/FILE-EXPLORER": "/tag/file-explorer",
    "/tag/PERFORMANCE": "/tag/performance",
    "/tag/KB5089573": "/tag/kb5089573",
    "/tag/INTERNET-SLOW": "/tag/internet-slow",
    "/tag/WINDOWS-SEARCH": "/tag/windows-search",
    "/tag/INDEXING-ISSUES": "/tag/indexing-issues",
    "/tag/FILE-SEARCH": "/tag/file-search",
    "/tag/SYSTEM-REPAIR": "/tag/system-repair",
    "/tag/WINDOWS-UPDATE-STUCK": "/tag/windows-update-stuck",
    "/tag/SOFTWAREDISTRIBUTION": "/tag/softwaredistribution",
    "/tag/AUDIO-ISSUES": "/tag/audio-issues",
    "/tag/VOLUME-CONTROL": "/tag/volume-control",
    "/tag/SOUND-PROBLEMS": "/tag/sound-problems"
},
  build: {
    format: "directory",
  },
  integrations: [
    mdx(),
    sitemap({
      filter: (page) =>
        !page.startsWith("https://www.praveentechworld.com/tag") &&
        !page.startsWith("https://www.praveentechworld.com/tags") &&
        !page.startsWith("https://www.praveentechworld.com/contact") &&
        !page.startsWith("https://www.praveentechworld.com/privacy") &&
        !page.startsWith("https://www.praveentechworld.com/author") &&
        !page.startsWith("https://www.praveentechworld.com/demo") &&
        !page.endsWith("/rss.xml") &&
        !page.endsWith("/rss") &&
        !page.endsWith("/portfolio"),
    }),
    pagefind(),
  ],
  markdown: {
    rehypePlugins: [rehypeExternalLinks],
    shikiConfig: {
      theme: "github-dark",
      wrap: true,
    },
  },
});
