export const AUTHOR_NAME = "Praveen Mishra";
export const AUTHOR_TITLE = "IT Ops Lead";
export const SITE_URL = "https://praveentechworld.com";

// 8 AUTO sites — direct form submission, zero outreach needed
export const AUTO_TARGETS = [
  {
    name: "New York Computer Help",
    url: "https://newyorkcomputerhelp.com/write-for-us/",
    type: "form",
    niche: "windows-it",
    da: "low",
    notes: "Direct blog post upload form with file upload",
  },
  {
    name: "Tech Universes",
    url: "https://www.techuniverses.com/write-for-us-technology/",
    type: "contact-form",
    niche: "tech",
    da: "low",
    notes: "Contact form for guest post submission",
  },
  {
    name: "Techy Dialogue",
    url: "https://www.techydialogue.com/write-for-us/",
    type: "account",
    niche: "tech",
    da: "low",
    notes: "Account registration + post submission tool",
  },
  {
    name: "SentiSight AI",
    url: "https://www.sentisight.ai/write-for-us/",
    type: "form",
    niche: "ai",
    da: "medium",
    notes: "Direct article upload form with file upload",
  },
  {
    name: "Setproduct",
    url: "https://www.setproduct.com/blog/submit-a-guest-post",
    type: "form",
    niche: "tech",
    da: "medium",
    notes: "Guest post submission system",
  },
  {
    name: "Novu Handbook",
    url: "https://handbook.novu.co/write-in-our-blog",
    type: "form",
    niche: "dev",
    da: "medium",
    notes: "Write-in-our-blog form — developer focused",
  },
  {
    name: "LogicSpice",
    url: "https://www.logicspice.com/submit-guest-post",
    type: "form",
    niche: "tech",
    da: "low",
    notes: "Direct guest post submission form",
  },
  {
    name: "Tech Labari",
    url: "https://techlabari.com/article-submission/",
    type: "account",
    niche: "tech",
    da: "low",
    notes: "Article submission system",
  },
];

// 44 EMAIL targets — need outreach, sorted by priority
export const EMAIL_TARGETS = [
  // TIER 1 — High DA
  {
    name: "News.va.gov",
    url: "https://news.va.gov/how-to-submit-a-guest-post/",
    email: "",
    niche: "government",
    da: "high",
    priority: 1,
    notes: ".gov backlink — highest authority possible. Pitch: IT/automation for veterans services",
    pitchTopic: "IT Operations",
    pitchAngle: "How automation improves government IT service delivery",
  },
  {
    name: "SitePoint",
    url: "https://www.sitepoint.com/write-for-us/",
    email: "",
    niche: "dev",
    da: "high",
    priority: 1,
    notes: "Major developer resource. Pitch: Astro builds, DB scripts, performance",
    pitchTopic: "Web Development",
    pitchAngle: "Technical tutorial on static site optimization or database scripting",
  },
  {
    name: "Katalon",
    url: "https://katalon.com/katalon-guest-post-guidelines",
    email: "",
    niche: "testing",
    da: "medium-high",
    priority: 1,
    notes: "Software testing platform. Pitch: test automation with AI agents",
    pitchTopic: "Test Automation",
    pitchAngle: "AI-generated test scripts and their failure modes",
  },
  {
    name: "Computer Support",
    url: "https://www.computersupport.com/guest-blogging",
    email: "editor@computersupport.com",
    niche: "windows-it",
    da: "medium-high",
    priority: 1,
    notes: "Directly in our Windows/IT niche. Pitch: Windows troubleshooting guides",
    pitchTopic: "Windows IT",
    pitchAngle: "Windows 11 troubleshooting or IT support automation",
  },
  {
    name: "Crescendo AI",
    url: "https://www.crescendo.ai/solutions/writeforus",
    email: "medha.mehta@crescendo.ai",
    niche: "ai",
    da: "medium",
    priority: 1,
    notes: "AI/CX platform. Pitch: AI automation for IT ops",
    pitchTopic: "AI Automation",
    pitchAngle: "AI agent pipeline automation and cost management",
  },
  // TIER 2 — Medium DA
  {
    name: "Flatlogic",
    url: "https://flatlogic.com/blog/submit-a-guest-post/",
    email: "",
    niche: "dev",
    da: "medium",
    priority: 2,
    notes: "React/Vue, databases, admin templates. Up to 3 do-follow links",
    pitchTopic: "Database Scripts",
    pitchAngle: "Building database audit tools with AI assistance",
  },
  {
    name: "LoginRadius",
    url: "https://www.loginradius.com/blog/guest-blog",
    email: "",
    niche: "tech",
    da: "medium-high",
    priority: 2,
    notes: "CIAM/tech blog. Broad tech audience",
    pitchTopic: "Tech Infrastructure",
    pitchAngle: "Cloud resource management and automation",
  },
  {
    name: "ICTworks",
    url: "https://www.ictworks.org/guest-post-guidelines/",
    email: "",
    niche: "tech",
    da: "medium",
    priority: 2,
    notes: "30K+ ICT4D professionals. Tech for development angle",
    pitchTopic: "IT Infrastructure",
    pitchAngle: "Cost-efficient IT ops for resource-constrained orgs",
  },
  {
    name: "GetMailbird",
    url: "https://www.getmailbird.com/write-for-us/",
    email: "",
    niche: "productivity",
    da: "medium",
    priority: 2,
    notes: "400K monthly visits. Productivity and workflow focus",
    pitchTopic: "Workflow Automation",
    pitchAngle: "Automating daily workflows with free tools",
  },
  {
    name: "Sphero",
    url: "https://sphero.com/pages/sphero-guest-post-guidelines",
    email: "",
    niche: "tech-edu",
    da: "medium",
    priority: 2,
    notes: "Tech education. Pitch: IT ops learning resources",
    pitchTopic: "IT Education",
    pitchAngle: "Practical IT troubleshooting skills for beginners",
  },
  {
    name: "ArcWeb",
    url: "https://www.arcweb.com/blog/guest-post-guidelines",
    email: "",
    niche: "tech",
    da: "medium",
    priority: 2,
    notes: "Technology research and consulting",
    pitchTopic: "Tech Strategy",
    pitchAngle: "AI automation adoption patterns in enterprises",
  },
  {
    name: "GanttPro",
    url: "https://blog.ganttpro.com/en/guideline-to-submit-a-guest-post-for-ganttpro/",
    email: "",
    niche: "productivity",
    da: "medium",
    priority: 2,
    notes: "Project management blog. Pitch: workflow automation",
    pitchTopic: "Project Management",
    pitchAngle: "Automating project reporting with AI scripts",
  },
  {
    name: "Rikkeisoft",
    url: "https://rikkeisoft.com/write-for-us/",
    email: "",
    niche: "dev",
    da: "medium",
    priority: 2,
    notes: "Software development company blog",
    pitchTopic: "Software Dev",
    pitchAngle: "AI-assisted coding: successes and failures",
  },
  {
    name: "ToolJunction",
    url: "https://www.tooljunction.io/write-for-us",
    email: "contact@tooljunction.io",
    niche: "tech",
    da: "medium",
    priority: 2,
    notes: "Contact form available",
    pitchTopic: "Tech Tools",
    pitchAngle: "Building CLI tools with AI assistance",
  },
  {
    name: "Serpstat",
    url: "https://serpstat.com/blog/how-to-submit-a-guest-post-to-serpstat-blog/",
    email: "",
    niche: "seo",
    da: "medium",
    priority: 2,
    notes: "SEO tool blog. Pitch: technical SEO case studies",
    pitchTopic: "Technical SEO",
    pitchAngle: "Fixing Google indexing errors — real case study",
  },
  {
    name: "RedEagle Tech",
    url: "https://redeagle.tech/blog/write-for-us",
    email: "editorial@redeagle.tech",
    niche: "tech",
    da: "medium",
    priority: 2,
    notes: "Tech blog. Pitch first via email",
    pitchTopic: "Tech Guides",
    pitchAngle: "Step-by-step tech troubleshooting guides",
  },
  {
    name: "Writers Helping Writers",
    url: "https://writershelpingwriters.net/guest-post-policy/",
    email: "",
    niche: "writing",
    da: "medium",
    priority: 2,
    notes: "Writing community. Pitch: technical writing tips",
    pitchTopic: "Technical Writing",
    pitchAngle: "How to write technical guides that non-techies understand",
  },
  {
    name: "Online Learning Consortium",
    url: "https://onlinelearningconsortium.org/olc-insights/submit/",
    email: "",
    niche: "education",
    da: "medium",
    priority: 2,
    notes: "Online education. Pitch: AI in higher ed IT",
    pitchTopic: "Education Technology",
    pitchAngle: "Protecting student data in AI-powered education",
  },
  {
    name: "Agile Alliance",
    url: "https://agilealliance.org/write-for-us-guest-post/",
    email: "",
    niche: "agile",
    da: "medium",
    priority: 2,
    notes: "Agile methodology community",
    pitchTopic: "Agile IT",
    pitchAngle: "Applying agile principles to IT operations automation",
  },
  {
    name: "Esri",
    url: "https://www.esri.com/about/newsroom/submit-article-guidelines",
    email: "",
    niche: "gis-tech",
    da: "high",
    priority: 2,
    notes: "GIS/tech company. Broad tech audience",
    pitchTopic: "Tech Infrastructure",
    pitchAngle: "Managing cloud infrastructure at scale",
  },
  // TIER 3 — Low DA but easy to get in
  {
    name: "CommandLinux",
    url: "https://commandlinux.com/write-for-us-tech-saas-ai-guest-post/",
    email: "",
    niche: "linux",
    da: "low",
    priority: 3,
    notes: "Linux/tech blog. Good niche fit",
    pitchTopic: "Linux/IT",
    pitchAngle: "Automating server health checks with scripts",
  },
  {
    name: "ComputerHen",
    url: "https://computerhen.com/write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Accepts via email/WhatsApp",
    pitchTopic: "Tech Guides",
    pitchAngle: "Windows troubleshooting step-by-step",
  },
  {
    name: "CrispyContent",
    url: "https://www.crispycontent.de/en/guest-post-guidelines",
    email: "",
    niche: "content",
    da: "medium",
    priority: 3,
    notes: "Content marketing blog",
    pitchTopic: "Content Strategy",
    pitchAngle: "Technical content that ranks: checklist approach",
  },
  {
    name: "Encyro",
    url: "https://www.encyro.com/help/article/59-can-i-submit-a-guest-post-for-your-blog",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Accepts guest posts via email",
    pitchTopic: "Tech Solutions",
    pitchAngle: "Practical fixes for common tech problems",
  },
  {
    name: "FixingGeek",
    url: "https://fixinggeek.com/guest-post/",
    email: "support@fixinggeek.com",
    niche: "windows-it",
    da: "low",
    priority: 3,
    notes: "Directly relevant. Fixing/fix guides niche",
    pitchTopic: "Windows Fixes",
    pitchAngle: "Windows 11 troubleshooting guide",
  },
  {
    name: "WindowsTechno",
    url: "https://windowstechno.com/submit-a-guest-post/",
    email: "admin@windowstechno.com",
    niche: "windows-it",
    da: "low",
    priority: 3,
    notes: "Paid guest posting. Direct Windows niche",
    pitchTopic: "Windows IT",
    pitchAngle: "Windows update troubleshooting and fixes",
  },
  {
    name: "XpiksApp",
    url: "https://xpiksapp.com/write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Accepts guest posts via email",
    pitchTopic: "Tech Productivity",
    pitchAngle: "Automating repetitive IT tasks",
  },
  {
    name: "GeekCodeLab",
    url: "https://geekcodelab.com/write-for-us/",
    email: "",
    niche: "dev",
    da: "low",
    priority: 3,
    notes: "Developer/write-for-us page",
    pitchTopic: "Development",
    pitchAngle: "Building CLI tools with Python and AI",
  },
  {
    name: "TechDogs",
    url: "https://www.techdogs.com/write-for-us",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Tech blog accepting contributions",
    pitchTopic: "Tech Guides",
    pitchAngle: "How-to guides for common tech problems",
  },
  {
    name: "TechChiefied",
    url: "https://techiefied.com/write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Tech blog, email submission",
    pitchTopic: "Tech Tips",
    pitchAngle: "Productivity automation with free tools",
  },
  {
    name: "TechResourcia",
    url: "https://techresourcia.com/write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Tech write-for-us page",
    pitchTopic: "Tech Resources",
    pitchAngle: "Essential IT tools and automation scripts",
  },
  {
    name: "W3Era",
    url: "https://www.w3era.com/blog/seo/write-for-us-technology-blogs/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "SEO/tech blog",
    pitchTopic: "Tech SEO",
    pitchAngle: "Technical SEO for IT/tech bloggers",
  },
  {
    name: "We Make It Happen Tech",
    url: "https://we-make-it-happen.tech/write-for-us/write-for-us-technology/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Tech write-for-us page",
    pitchTopic: "Tech Innovation",
    pitchAngle: "AI automation in IT operations",
  },
  {
    name: "OutrightCRM",
    url: "https://store.outrightcrm.com/write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "CRM/tech blog",
    pitchTopic: "CRM Tech",
    pitchAngle: "Automating CRM data workflows",
  },
  {
    name: "Tech ClickDo",
    url: "https://tech.clickdo.co.uk/technology-write-for-us/",
    email: "",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "UK tech blog",
    pitchTopic: "Tech Guides",
    pitchAngle: "IT troubleshooting and automation",
  },
  {
    name: "AI-Hunter",
    url: "https://ai-hunter.io/ai-guest-post-and-article-submission/",
    email: "",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "$25 for guest post, $49 for sponsored",
    pitchTopic: "AI Tools",
    pitchAngle: "AI agent pipelines and cost optimization",
  },
  {
    name: "AIToolMind",
    url: "https://aitoolmind.com/write-for-us/",
    email: "",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "Contact page, 24-48h review",
    pitchTopic: "AI Tools",
    pitchAngle: "Practical AI tools for IT operations",
  },
  {
    name: "AITude",
    url: "https://www.aitude.com/write-for-us/",
    email: "hello@aitude.com",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "AI blog, email submission",
    pitchTopic: "AI",
    pitchAngle: "Using AI to automate sysadmin tasks",
  },
  {
    name: "AIAgentStore",
    url: "https://aiagentstore.ai/guest-post",
    email: "",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "AI agent marketplace",
    pitchTopic: "AI Agents",
    pitchAngle: "Building autonomous agents that actually work",
  },
  {
    name: "RankBloom",
    url: "https://rankbloomoutreach.com/blog/write-for-us-ai-submit-a-guest-post",
    email: "",
    niche: "seo",
    da: "low",
    priority: 3,
    notes: "SEO outreach blog",
    pitchTopic: "SEO",
    pitchAngle: "Link building for new tech sites",
  },
  {
    name: "TubeOnAI",
    url: "https://tubeonai.com/write-for-us/",
    email: "",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "AI content site",
    pitchTopic: "AI",
    pitchAngle: "AI automation guides and tutorials",
  },
  {
    name: "Wavel AI",
    url: "https://wavel.ai/write-for-us",
    email: "",
    niche: "ai",
    da: "low",
    priority: 3,
    notes: "AI platform blog",
    pitchTopic: "AI",
    pitchAngle: "Practical AI implementation case studies",
  },
  {
    name: "JustTotalTech",
    url: "https://justtotaltech.com/write-for-us/",
    email: "sam@justtotaltech.com",
    niche: "tech",
    da: "low",
    priority: 3,
    notes: "Email pitch to sam@justtotaltech.com",
    pitchTopic: "Tech",
    pitchAngle: "Total tech solutions and automation",
  },
];

// Best articles from our site to pitch, organized by niche
export const ARTICLES_BY_NICHE = {
  "windows-it": [
    {
      title: "Windows 11 Update Errors in 2026 — Step-by-Step Fix Guide",
      url: "/articles/fix-windows-11-update-errors-2026-troubleshooting",
      description: "Complete Windows 11 update troubleshooting guide",
    },
    {
      title: "Critical: Windows 11 KB5089573 Breaks Internet - Fix It in 3 Steps",
      url: "/articles/windows-11-kb5089573-update-errors-slow-internet-fix",
      description: "Fix for the June 2026 Windows update that broke internet",
    },
    {
      title: "Stop Reinstalling Windows — Try These 7 Fixes First",
      url: "/articles/will-reinstalling-windows-fix-slow-performance-issues",
      description: "Windows performance fixes before reinstalling",
    },
    {
      title: "Will Reinstalling Windows Fix Blue Screen Errors?",
      url: "/articles/will-reinstalling-windows-fix-blue-screen-errors",
      description: "BSOD troubleshooting guide",
    },
  ],
  ai: [
    {
      title: "We Broke the AI Chatbox: Architecture, Code, and Benchmarks",
      url: "/articles/breaking-the-ai-chatbox-berkeley-students-build-autonomous-agents",
      description: "Technical deep-dive into autonomous LLM agents",
    },
    {
      title: "Cost Caps & Loop Guards in LLM Agent Pipelines",
      url: "/articles/cost-caps-retry-limits-for-llm-agent-pipelines",
      description: "Preventing runaway API costs in AI agent pipelines",
    },
    {
      title: "DeepSeek API Cost Tracker Saved Me $2K/Month",
      url: "/articles/deepseek-api-cost-tracker-scripts",
      description: "Building an AI cost tracking dashboard",
    },
    {
      title: "Building a CLI Tool to Automate Spreadsheet Data Cleaning with DeepSeek",
      url: "/articles/building-a-cli-tool-to-automate-spreadsheet-data-cleaning-with-deepseek",
      description: "AI-assisted tool building case study",
    },
  ],
  dev: [
    {
      title: "Why We Migrated Away from Docker Desktop in 2026",
      url: "/articles/why-we-migrated-away-from-docker-desktop",
      description: "Docker alternatives comparison with benchmarks",
    },
    {
      title: "Fix Docker Volume Permission Denied Errors",
      url: "/articles/fix-docker-volume-permission-denied-errors-on-windows-linux",
      description: "Docker troubleshooting guide",
    },
    {
      title: "I Built a Database Audit Script with DeepSeek",
      url: "/articles/non-developer-built-database-audit-script-with-deepseek",
      description: "Non-developer uses AI to build a database tool",
    },
  ],
  tech: [
    {
      title: "How to Fix Google Indexing Errors: Crawled Not Indexed",
      url: "/articles/how-to-fix-google-indexing-errors-crawled-not-indexed",
      description: "Complete guide to fixing Google indexing issues",
    },
    {
      title: "GA4 Not Tracking Visitors? 12 Troubleshooting Steps (98% Fix Rate)",
      url: "/articles/ga4-not-tracking-visitors-12-troubleshooting-steps",
      description: "GA4 tracking troubleshooting guide",
    },
    {
      title: "Website Speed Upgrades: Fix Crawling Delays and Core Web Vitals",
      url: "/articles/website-speed-upgrades-fix-crawling-delays-and-core-web-vitals",
      description: "Website performance optimization guide",
    },
    {
      title: "How to Automate Your Daily Workflow with Free Tools in 2026",
      url: "/articles/how-to-automate-your-daily-workflow-with-free-tools-in-2026-complete-guide",
      description: "Workflow automation with free tools",
    },
  ],
  seo: [
    {
      title: "How to Fix Google Indexing Errors: Crawled Not Indexed",
      url: "/articles/how-to-fix-google-indexing-errors-crawled-not-indexed",
      description: "Complete guide to fixing Google indexing issues",
    },
    {
      title: "Sitemap Submitted but Pages Stay Undiscovered?",
      url: "/articles/sitemap-submitted-but-pages-undiscovered-robotstxt-check",
      description: "Sitemap troubleshooting guide",
    },
    {
      title: "Technical SEO Checklist: 15 Issues Beginners Miss",
      url: "/articles/technical-seo-checklist-for-beginners-fix-these-issues-to-rank-better",
      description: "Technical SEO fundamentals",
    },
  ],
  productivity: [
    {
      title: "How to Automate Your Daily Workflow with Free Tools in 2026",
      url: "/articles/how-to-automate-your-daily-workflow-with-free-tools-in-2026-complete-guide",
      description: "Workflow automation with free tools",
    },
    {
      title: "AI-Powered Expense Report Automation for Office Workers",
      url: "/articles/ai-powered-expense-report-automation-for-office-workers-no-code-solutions",
      description: "No-code automation for office tasks",
    },
  ],
};

export function getArticleUrl(slug) {
  return `${SITE_URL}${slug}`;
}
