import fs from "fs";
import path from "path";
import { ensureDir, log } from "./shared.mjs";

const REPORTS_DIR = path.resolve(import.meta.dirname, "../../reports");

export function getReportPath() {
  return path.join(REPORTS_DIR, "report.md");
}

export function buildReport({ articlesToday, articlesTotal, topicsApproved, topicsRejected, supplyChainIssues, improvements, goalsMet, goalsMissed }) {
  const lines = [
    `# PraveenTechWorld — System Report`,
    `**Generated:** ${new Date().toISOString()}`,
    `**Session:** ${new Date().toLocaleDateString()}`,
    "",
    "## Today's Production",
    `- Articles published today: ${articlesToday}`,
    `- Total articles on site: ${articlesTotal}`,
    `- Topics approved: ${topicsApproved}`,
    `- Topics rejected: ${topicsRejected}`,
    "",
    "## Supply Chain Health",
  ];

  if (supplyChainIssues && supplyChainIssues.length) {
    supplyChainIssues.forEach((i) => lines.push(`- ⚠️ ${i}`));
  } else {
    lines.push("- ✅ No issues detected");
  }

  lines.push("", "## Marginal Improvements Suggested");

  if (improvements && improvements.length) {
    improvements.forEach((i) => lines.push(`- ${i}`));
  } else {
    lines.push("- None at this time");
  }

  lines.push("", "## Goals Status");
  if (goalsMet && goalsMet.length) {
    lines.push("", "### Met");
    goalsMet.forEach((g) => lines.push(`- ✅ ${g}`));
  }
  if (goalsMissed && goalsMissed.length) {
    lines.push("", "### Missed");
    goalsMissed.forEach((g) => lines.push(`- ❌ ${g}`));
  }

  lines.push("", "---", "", "*Report auto-generated by Boss/CEO Agent*");

  return lines.join("\n");
}

export function writeReport(content) {
  ensureDir(REPORTS_DIR);
  const filePath = getReportPath();
  fs.writeFileSync(filePath, content, "utf-8");
  log(`  Report written: ${filePath}`);
  return filePath;
}

export function reportExists() {
  return fs.existsSync(getReportPath());
}

export function reportAgeHours() {
  if (!reportExists()) return Infinity;
  const stat = fs.statSync(getReportPath());
  return (Date.now() - stat.mtimeMs) / (1000 * 60 * 60);
}

export function markReportOpened() {
  const flagPath = path.join(REPORTS_DIR, ".boss_opened");
  fs.writeFileSync(flagPath, new Date().toISOString(), "utf-8");
}

export function wasReportOpened() {
  const flagPath = path.join(REPORTS_DIR, ".boss_opened");
  if (!fs.existsSync(flagPath)) return false;
  const flagTime = new Date(fs.readFileSync(flagPath, "utf-8")).getTime();
  const reportModified = fs.statSync(getReportPath()).mtimeMs;
  return flagTime >= reportModified;
}

export function writeGoal(dateStr, content) {
  const dir = path.join(REPORTS_DIR, "goals", "daily");
  ensureDir(dir);
  const filePath = path.join(dir, `${dateStr}.md`);
  fs.writeFileSync(filePath, content, "utf-8");
  return filePath;
}

export function writeWeeklyGoal(weekStr, content) {
  const dir = path.join(REPORTS_DIR, "goals", "weekly");
  ensureDir(dir);
  const filePath = path.join(dir, `${weekStr}.md`);
  fs.writeFileSync(filePath, content, "utf-8");
  return filePath;
}
