const API_BASE = "https://api.telegram.org";

function getConfig() {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  const chatId = process.env.TELEGRAM_CHAT_ID;
  if (!token || !chatId) return null;
  return { token, chatId };
}

async function sendMessage(text, parseMode = "HTML") {
  const config = getConfig();
  if (!config) return false;

  const url = `${API_BASE}/bot${config.token}/sendMessage`;
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chat_id: config.chatId,
        text,
        parse_mode: parseMode,
        disable_web_page_preview: false,
      }),
    });
    if (!res.ok) {
      const err = await res.text();
      console.error(`Telegram API error: ${err}`);
      return false;
    }
    return true;
  } catch (err) {
    console.error(`Telegram send failed: ${err.message}`);
    return false;
  }
}

export async function notifyOpportunity(category, count) {
  const text = [
    `<b>🔍 Opportunity Report Ready</b>`,
    ``,
    `<b>Category:</b> ${category}`,
    `<b>Items found:</b> ${count}`,
    ``,
    `Run <code>node research/agents/research.mjs ${category}</code> to research.`,
  ].join("\n");
  return sendMessage(text);
}

export async function notifyBriefReady(topic, filename) {
  const text = [
    `<b>📝 Research Brief Ready</b>`,
    ``,
    `<b>Topic:</b> ${topic}`,
    `<b>File:</b> ${filename}`,
    ``,
    `Run <code>node research/agents/draft.mjs ${filename.replace(/\.md$/, "")}</code> to generate a draft.`,
  ].join("\n");
  return sendMessage(text);
}

export async function notifyDraftReady(topic, filename) {
  const text = [
    `<b>✍️ Draft Article Ready</b>`,
    ``,
    `<b>Topic:</b> ${topic}`,
    `<b>File:</b> ${filename}`,
    ``,
    `<b>⚠️ Human review required before publishing.</b>`,
    ``,
    `Edit the file in <code>research/reports/drafts/</code> and move to <code>src/content/articles/</code> when ready.`,
  ].join("\n");
  return sendMessage(text);
}

export async function notifyWeeklyDigest(summary) {
  const text = [
    `<b>📊 Weekly Digest — PraveenTechWorld</b>`,
    ``,
    summary,
    ``,
    `<i>Generated by Research Intelligence System</i>`,
  ].join("\n");
  return sendMessage(text);
}

export async function notifyError(context, errorMessage) {
  const text = [
    `<b>⚠️ Research System Error</b>`,
    ``,
    `<b>Context:</b> ${context}`,
    `<b>Error:</b> ${errorMessage}`,
  ].join("\n");
  return sendMessage(text);
}
