#!/usr/bin/env node

import { readFileSync, readdirSync, statSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(__dirname, "..");
const REPORTS_DIR = resolve(ROOT_DIR, "research/reports");

function loadEnv() {
  const envPath = resolve(ROOT_DIR, ".env");
  try {
    const content = readFileSync(envPath, "utf-8");
    for (const line of content.split("\n")) {
      const t = line.trim();
      if (t && !t.startsWith("#")) {
        const idx = t.indexOf("=");
        if (idx > 0) {
          const key = t.slice(0, idx).trim();
          let val = t.slice(idx + 1).trim();
          if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
          if (!process.env[key]) process.env[key] = val;
        }
      }
    }
  } catch { /* ignore */ }
}

loadEnv();

const SEVEN_DAYS = 7 * 24 * 60 * 60 * 1000;
const now = Date.now();

function getRecentFiles(dir) {
  try {
    const files = readdirSync(dir);
    return files.filter((f) => {
      const fp = resolve(dir, f);
      return statSync(fp).mtimeMs > now - SEVEN_DAYS;
    });
  } catch {
    return [];
  }
}

const oppDir = resolve(REPORTS_DIR, "opportunities");
const briefDir = resolve(REPORTS_DIR, "briefs");
const draftDir = resolve(REPORTS_DIR, "drafts");

const recentOpps = getRecentFiles(oppDir);
const recentBriefs = getRecentFiles(briefDir);
const recentDrafts = getRecentFiles(draftDir);

const lines = [`📊 <b>Weekly Digest — ${new Date().toISOString().slice(0, 10)}</b>`, ""];

if (recentOpps.length > 0) {
  lines.push(`<b>🔍 Opportunities found:</b>`);
  for (const f of recentOpps) {
    const fp = resolve(oppDir, f);
    try {
      const content = readFileSync(fp, "utf-8");
      const line1 = content.split("\n")[0];
      const catMatch = line1.match(/^# Opportunity Report:\s+(.+)/);
      const countMatch = content.match(/^Items found:\s+(\d+)/m);
      function titleCase(str) {
        return str.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
          .replace(/\bAi\b/g, "AI").replace(/\bApi\b/g, "API")
          .replace(/\bSms\b/g, "SMS").replace(/\bRss\b/g, "RSS");
      }
      const cat = catMatch ? titleCase(catMatch[1]) : f;
      const count = countMatch ? countMatch[1] : "?";
      lines.push(`  • ${cat}: ${count} items`);
    } catch {
      lines.push(`  • ${f}`);
    }
  }
} else {
  lines.push(`<b>🔍 Opportunities:</b> None in the past 7 days`);
}

lines.push("");

if (recentBriefs.length > 0) {
  lines.push(`<b>📝 Research briefs:</b>`);
  for (const f of recentBriefs) {
    lines.push(`  • ${f.replace(/\.md$/, "").replace(/-/g, " ")}`);
  }
} else {
  lines.push(`<b>📝 Research briefs:</b> None`);
}

lines.push("");

if (recentDrafts.length > 0) {
  lines.push(`<b>✍️ Drafts ready for review:</b>`);
  for (const f of recentDrafts) {
    if (!f.includes("outline")) {
      lines.push(`  • ${f.replace(/\.md$/, "").replace(/-/g, " ")}`);
    }
  }
} else {
  lines.push(`<b>✍️ Drafts:</b> None`);
}

lines.push("");
lines.push("<i>Generated by Research Intelligence System</i>");

const summary = lines.join("\n");
console.log(summary);

const botUrl = new URL("bot.mjs", import.meta.url).href;
const { notifyWeeklyDigest } = await import(botUrl);
const sent = await notifyWeeklyDigest(summary);
if (sent) {
  console.log("Digest sent to Telegram.");
} else {
  console.log("Digest not sent (Telegram not configured).");
}
